"""Printable A4 Code 128 separator sheet generation (PRD FR-8).

Everything is produced locally with PyMuPDF and ZXing-C++ — no network access,
no downloaded fonts, no external barcode service.
"""

from __future__ import annotations

from pathlib import Path

try:
    import pymupdf
except ImportError:  # pragma: no cover
    import fitz as pymupdf  # type: ignore[no-redef]

import zxingcpp

from .barcode import validate_separator_value

# A4 at 72 pt/inch.
A4_WIDTH_PT = 595.276
A4_HEIGHT_PT = 841.890

HEADING = "DOCUMENT SEPARATOR"
INSTRUCTIONS = (
    "Place this sheet between documents before scanning.",
    "This page is detected automatically and removed from the output.",
    "Do not write on or fold this sheet. Keep the area around the barcode clear.",
)


class SeparatorGenerationError(Exception):
    """Raised when a separator sheet cannot be produced."""


def _barcode_png(value: str, scale: int = 4) -> bytes:
    """Render ``value`` as a Code 128 barcode PNG with quiet zones."""

    try:
        barcode = zxingcpp.create_barcode(value, zxingcpp.BarcodeFormat.Code128)
        try:
            image = zxingcpp.write_barcode_to_image(
                barcode, size_hint=scale, with_hrt=False, with_quiet_zones=True
            )
        except TypeError:
            image = zxingcpp.write_barcode_to_image(
                barcode, scale=scale, add_hrt=False, add_quiet_zones=True
            )
    except Exception as exc:  # pragma: no cover - depends on zxing build
        raise SeparatorGenerationError(
            f"The barcode could not be generated for this value: {exc}"
        ) from exc

    # zxingcpp.Image exposes the buffer protocol; convert via PyMuPDF Pixmap.
    try:
        import numpy as np

        array = np.array(image, copy=False)
        if array.ndim == 3 and array.shape[2] == 1:
            array = array[:, :, 0]
        height, width = array.shape[:2]
        if array.ndim == 2:
            pixmap = pymupdf.Pixmap(
                pymupdf.csGRAY, width, height, bytes(array.tobytes()), False
            )
        else:  # pragma: no cover - zxing returns grayscale today
            pixmap = pymupdf.Pixmap(
                pymupdf.csRGB, width, height, bytes(array[:, :, :3].tobytes()), False
            )
        try:
            return pixmap.tobytes("png")
        finally:
            del pixmap
    except SeparatorGenerationError:
        raise
    except Exception as exc:
        raise SeparatorGenerationError(
            f"The barcode image could not be prepared: {exc}"
        ) from exc


def create_separator_pdf(value: str, destination: Path) -> Path:
    """Write a print-ready A4 separator sheet for ``value`` to ``destination``."""

    valid, message = validate_separator_value(value)
    if not valid:
        raise SeparatorGenerationError(message)

    destination = Path(destination)
    png_bytes = _barcode_png(value)

    document = pymupdf.open()
    try:
        page = document.new_page(width=A4_WIDTH_PT, height=A4_HEIGHT_PT)

        # --- Heading -------------------------------------------------
        heading_rect = pymupdf.Rect(56, 90, A4_WIDTH_PT - 56, 160)
        page.insert_textbox(
            heading_rect,
            HEADING,
            fontname="hebo",
            fontsize=30,
            align=pymupdf.TEXT_ALIGN_CENTER,
        )

        # --- Barcode with generous quiet zone ------------------------
        barcode_width = A4_WIDTH_PT - 2 * 110
        barcode_rect = pymupdf.Rect(
            110,
            250,
            110 + barcode_width,
            250 + 170,
        )
        # White backing box guarantees the quiet zone even on tinted paper.
        quiet_rect = pymupdf.Rect(
            barcode_rect.x0 - 34,
            barcode_rect.y0 - 34,
            barcode_rect.x1 + 34,
            barcode_rect.y1 + 34,
        )
        page.draw_rect(quiet_rect, color=None, fill=(1, 1, 1))
        page.insert_image(barcode_rect, stream=png_bytes, keep_proportion=True)

        # --- Human-readable value ------------------------------------
        value_rect = pymupdf.Rect(56, barcode_rect.y1 + 46, A4_WIDTH_PT - 56, barcode_rect.y1 + 96)
        page.insert_textbox(
            value_rect,
            value,
            fontname="cobo",
            fontsize=19,
            align=pymupdf.TEXT_ALIGN_CENTER,
        )

        # --- Instructions --------------------------------------------
        instructions_rect = pymupdf.Rect(70, 600, A4_WIDTH_PT - 70, 730)
        page.insert_textbox(
            instructions_rect,
            "\n".join(INSTRUCTIONS),
            fontname="helv",
            fontsize=11.5,
            align=pymupdf.TEXT_ALIGN_CENTER,
            lineheight=1.6,
        )

        footer_rect = pymupdf.Rect(56, A4_HEIGHT_PT - 74, A4_WIDTH_PT - 56, A4_HEIGHT_PT - 44)
        page.insert_textbox(
            footer_rect,
            "Generated by JuaDex PDFs Separator \u2014 Code 128",
            fontname="helv",
            fontsize=8.5,
            color=(0.42, 0.42, 0.42),
            align=pymupdf.TEXT_ALIGN_CENTER,
        )

        destination.parent.mkdir(parents=True, exist_ok=True)
        document.save(str(destination), garbage=4, deflate=True)
    except SeparatorGenerationError:
        raise
    except Exception as exc:
        raise SeparatorGenerationError(f"The separator sheet could not be saved: {exc}") from exc
    finally:
        document.close()

    return destination


__all__ = ["SeparatorGenerationError", "create_separator_pdf"]
