"""Collect dependency licence texts into ``LICENSES/`` for distribution.

Run from the project root:

    python packaging/collect_licenses.py

The script reads licence files straight from the installed distributions, so
the shipped texts always match the versions actually packaged.
"""

from __future__ import annotations

import importlib.metadata as metadata
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT / "LICENSES"

# Distribution name -> file name to write.
PACKAGES = {
    "PyMuPDF": "PyMuPDF-AGPL-3.0.txt",
    "PySide6-Essentials": "PySide6-LGPL-3.0.txt",
    "zxing-cpp": "zxing-cpp-Apache-2.0.txt",
    "numpy": "NumPy-BSD-3-Clause.txt",
    "pillow": "Pillow-MIT-CMU.txt",
}

LICENSE_FILE_HINTS = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "AUTHORS")


def find_license_text(distribution_name: str) -> tuple[str, str]:
    """Return ``(version, licence_text)`` for an installed distribution."""

    try:
        dist = metadata.distribution(distribution_name)
    except metadata.PackageNotFoundError:
        return "not installed", ""

    version = dist.version
    chunks: list[str] = []

    for file in dist.files or []:
        name = Path(str(file)).name.upper()
        if not any(name.startswith(hint) for hint in LICENSE_FILE_HINTS):
            continue
        if name.endswith((".py", ".pyc", ".so", ".pyd", ".dll")):
            continue
        try:
            text = dist.read_text(str(file))
        except (OSError, UnicodeDecodeError):
            continue
        if text and text.strip():
            chunks.append(f"----- {file} -----\n\n{text.strip()}")

    if not chunks:
        # Fall back to the declared licence metadata.
        meta = dist.metadata
        declared = (
            meta.get("License-Expression")
            or meta.get("License")
            or "; ".join(
                c for c in (meta.get_all("Classifier") or []) if "License" in c
            )
            or "See the project homepage."
        )
        chunks.append(f"Declared licence: {declared}")

    return version, "\n\n".join(chunks)


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    index: list[str] = [
        "# Bundled dependency licences",
        "",
        "Generated by packaging/collect_licenses.py. Do not edit by hand.",
        "",
    ]

    missing: list[str] = []
    for package, filename in PACKAGES.items():
        version, text = find_license_text(package)
        if not text:
            missing.append(package)
            continue
        header = (
            f"{package} {version}\n"
            f"{'=' * (len(package) + len(version) + 1)}\n\n"
        )
        (OUTPUT_DIR / filename).write_text(header + text + "\n", encoding="utf-8")
        index.append(f"* **{package}** {version} - `{filename}`")
        print(f"wrote {filename} ({package} {version})")

    (OUTPUT_DIR / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")

    if missing:
        print(
            "\nWARNING: not installed, licence text not collected: "
            + ", ".join(missing),
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
